#!/usr/bin/env python3
"""Write src/language_en.cpp and src/language_fr.cpp from the translation tables in this folder.

The interface texts in the code are German and go through ui(); the English ones are looked up by the German text.
Every table (*.py next to this script) defines T = {German text: English text}. Each module keeps its own table
(lochraster.py, frontpanel.py, pcb.py, ...), so that work on different modules does not touch the same lines.
The core tests fail for any ui() text without an English entry.
"""
from pathlib import Path
import runpy

here = Path(__file__).resolve().parent
root = here.parents[1]
texts = {}
french = {}
for table in sorted(here.glob('*.py')):
    if table.name == 'generate.py':
        continue
    values = runpy.run_path(str(table))
    for german, english in values.get('T', {}).items():
        if german in texts and texts[german] != english:
            raise SystemExit(f'{table.name}: "{german}" is already translated differently: "{texts[german]}"')
        texts[german] = english
    # French tables (*_fr.py) define FR = {German text: French text}; missing French texts are shown in English.
    for german, text in values.get('FR', {}).items():
        if german in french and french[german] != text:
            raise SystemExit(f'{table.name}: "{german}" is already translated differently: "{french[german]}"')
        french[german] = text


def c(text):
    return text.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t')


lines = ['// English interface texts, looked up by the German text of the code (see language.h).',
         '// Generated by scripts/translations/generate.py from the tables in scripts/translations/; do not edit.',
         '#include "language.h"', 'namespace openloch {', 'extern const char *const englishTexts[][2];',
         'extern const int englishTextCount;', 'const char *const englishTexts[][2]={']
lines += [f'    {{"{c(german)}","{c(english)}"}},' for german, english in texts.items()]
lines += ['};', 'const int englishTextCount=int(sizeof(englishTexts)/sizeof(englishTexts[0]));', '}', '']
root.joinpath('src/language_en.cpp').write_text('\n'.join(lines), encoding='utf-8')
print(f'{len(texts)} texts written to src/language_en.cpp')
lines = ['// French interface texts, looked up by the German text of the code (see language.h).',
         '// Generated by scripts/translations/generate.py from the tables in scripts/translations/; do not edit.',
         '#include "language.h"', 'namespace openloch {', 'extern const char *const frenchTexts[][2];',
         'extern const int frenchTextCount;', 'const char *const frenchTexts[][2]={']
lines += [f'    {{"{c(german)}","{c(text)}"}},' for german, text in french.items()]
lines += ['};', 'const int frenchTextCount=int(sizeof(frenchTexts)/sizeof(frenchTexts[0]));', '}', '']
root.joinpath('src/language_fr.cpp').write_text('\n'.join(lines), encoding='utf-8')
print(f'{len(french)} texts written to src/language_fr.cpp')
